### ISSUE TITLE
ALSA lib pcm_asym.c:105:(_snd_pcm_asym_open) capture slave is not defined

### ISSUE THREAD

**Issue by thekv** [TobKra96/music_led_strip_control#202]
The project is awesome thanks, not sure if its still development?

For me the non-audio Music Effects are working but I cant get the Music Effects working. The microphone seems to be detected and I can save it as a device in the Web gui.  When i run manually:

```shell
sudo python3 main.py
INFO     - __main__                       - Initializing MLSC...
ALSA lib pcm_asym.c:105:(_snd_pcm_asym_open) capture slave is not defined
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

INFO     - __main__                       - Initialization finished.
INFO     - __main__                       - MLSC started...
INFO     - libs.audio_process_service     - Found the following audio sources:
INFO     - libs.audio_process_service     - Selected Device: 0 - USB PnP Sound Device: Audio (hw:0,0) - 44100.0 Hz
INFO     - libs.device                    - Starting device: KvsPi
INFO     - libs.output_service            - Starting Output service... Device: KvsPi
INFO     - libs.effect_service            - Starting Effect Service component from device: KvsPi
INFO     - libs.effect_service            - Effects component started. Device: KvsPi
INFO     - waitress                       - Serving on http://0.0.0.0:8080`
``` 

When I try and activate a Music Effect I get the following:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/share/music_led_strip_control/server/libs/effect_service.py", line 104, in start
    self.effect_routine()
  File "/share/music_led_strip_control/server/libs/effect_service.py", line 168, in effect_routine
    self._initialized_effects[self._current_effect].run()
  File "/share/music_led_strip_control/server/libs/effects/effect_scroll.py", line 40, in run
    lows_max = float(np.max(lows)) * effect_config["lows_multiplier"]
                     ^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amax
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 2820, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity

``` 

I had a lot of issues with the initial setup and this is the 'closest' point to getting it working. I ran the automated script with current Pi OS Lite 64 and 32 and the Master and Dev 2.3 but many dependencies did not install, and I had to manually install python3-pyaudio python3-numpy python3-coloredlogs python3-jsonschema python3-scipy. Also tried sudo pip3 install -r requirements.txt which I had no luck with.

Anyway any help here appreciated.

Thanks

**Comment by thekv** [comment]
Not sure what happened but its working now so closed. For my own future reference still getting:

```shell
ALSA lib pcm_asym.c:105:(_snd_pcm_asym_open) capture slave is not defined
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
``` 

on startup but it seems to be irrelevant to operation.  No longer receiving the above mentioned error on Music Effects.

Thanks for the awesome project.
